# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0      
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      - clang-5.0
      - libc++-dev
      - libc++abi-dev
      - libclang-5.0-dev
      - libclang-common-5.0-dev
      - libclang1-5.0

      # pip3
      - python3-pip

env:
  global:
    - secure: "yWrVHDFf2oMQUx+u1HzCihiU81yJ5JSLegFfqcIqPDIxwYrtRD5482zPF5yi1T2RK7JsKP24eiPwPWRBpGlqdqTUpSbZMBF5LFfb/TqAk7KYjrXyg0aHwY4g6sy5HkDM3FmNicD5gfTUfSQvNM1Xnq5zOGhYf/zNaUybbtc9uNJqDQGtH3DnyOORv8/dxzEELuU24V5LwRt2LELDLvoDlkJLGsvSfDeZYXDjcgtrJ5Hbt+zBu8WIkgqHFJY0MxGe7CSXly25rde3kLZx4ikGoHY4PP90GAAcuuKrfiW5lda0f71BU/1jYEWVy+B3eId8tG00qz4L2I3+ups5Zte2JA1xo2S8F2jHQSEAefMDlFNXcx49NY32FFtjFM9j8MrE9m58WCRCdsWmGKU9BRTKKYDGzi8kuG8VpPVxEg2tH21E/XmR2LHptM/G6QAgI2l2iZHAzx7IZJG/Ip41NB6aGwLOA0Fh3sbIpuDCw8IC2HcBUeKI65pISsFQMvykUIUcRTOM8vHXGzwZ5mkydFeCsYdUhGHf03wKWYrKjIUSJF2VkFB04XHoII/36ggMYoV7/5Lhqsjhcw3aGI+9uUG/zW18S5zSvYRFJdfY/cy5UQt5ofAeChxqxwQVGPiXr3s1ekrHL2Gf84XVgXydhYcU0S54qUnIa8ohP/Fe6ynQwV8="

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=libcxx-fpic-hid-sections INSTALL=--strip

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5 INSTALL=--strip

    - os: linux
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon INSTALL=--strip

    # }

    # OSX {

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12 INSTALL=--install

    - os: osx
      osx_image: xcode9
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-11-0-arm64-dep-9-0-device-libcxx-hid-sections INSTALL=--install

    # }

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false


# See https://docs.travis-ci.com/user/private-dependencies/#API-Token
# CI_USER_TOKEN is added to .travis.yml settings
before_install:

  # Add '--quiet' to avoid leaking the token to logs
  - git submodule update --init --recursive --quiet

  # https://stackoverflow.com/a/38790045
  - bin/travis_clang_links.sh
  
install:
  - source bin/hunter_env.sh

script:

  # '--ios-{multiarch,combined}' do nothing for non-iOS builds
  - bin/build-travis.sh ${TOOLCHAIN} ${CONFIG} ${INSTALL}

branches:
  except:
    - /^pr\..*/
