# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      # pip3
      - python3-pip

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5 INSTALL=--strip

    - os: linux
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon INSTALL=--strip

    # }

    # OSX {

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12 INSTALL=--install

    - os: osx
      osx_image: xcode9
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-11-0-arm64-dep-9-0-device-libcxx-hid-sections INSTALL=--install

    # }

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false

install:
  - source bin/hunter_env.sh

script:

    # '--ios-{multiarch,combined}' do nothing for non-iOS builds
    - >
      polly.py
      --toolchain ${TOOLCHAIN}
      --config ${CONFIG}
      --verbose
      --ios-multiarch --ios-combined
      --fwd
      GAUZE_ANDROID_USE_EMULATOR=YES
      HUNTER_USE_CACHE_SERVERS=YES
      HUNTER_DISABLE_BUILDS=NO
      HUNTER_SUPPRESS_LIST_OF_FILES=ON
      --archive drishti
      --jobs 2
      --test
      ${INSTALL}

branches:
  except:
    - /^pr\..*/
