image: Visual Studio 2015

environment:

  matrix:

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      CONFIG: Debug

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      CONFIG: Debug

install:
  - cmd: bin\hunter_env.cmd

build_script:

  - cmd: bin\build-appveyor.cmd "%CONFIG%" "%TOOLCHAIN%"

branches:
  except:
    - /^pr\..*/
